### PR TITLE
Feature: Füge Zeitmesser-Checkliste hinzu

### LINKED ISSUE #566: Feature: Zeitnehmer Checkliste
Ein neuer Report ist sehr hilfreich, der das abhaken für  Zeitnehmer erleichtert (wenn z.b. jemand im Ziel ist oder zur Kennzeichnung von NAS/NIZ usw. auf Papier. 
Viele (auch ich) verwenden dies zusätzlich zum Programm als schnelle Übersicht auch nachher als Grundlage zur Absprache mit dem Schiedsrichter. 
Es soll ein 3-Spalten System geben, wo die Startnumer jeweils in der Mitte steht. Links und rechts davon kann man sich dann (nach persönlichem Belieben) die Notizen dazu machen. 

Beispiel: 
grafik

### PR DESCRIPTION
**Pull request by mstenz**
fixes #566

### CODE REVIEW

**Comment by mstenz** [comment]
the Unit-Test is yet missing. feedback welcome.

**Comment by mstenz** [comment]
unit Test is now in - still waiting for more feedback before we should merge it.

**Comment by mstenz** [comment]
Tested the list. Works as expected.

**Review by svenflossmann — CHANGES_REQUESTED** [review]
Wie besprochen: Noch den Tabellenkopf weg machen ...

**Comment by mstenz** [comment]
> Wie besprochen: Noch den Tabellenkopf weg machen ...

done

**Review by svenflossmann — APPROVED** [review]

**Pull request merged**
